services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend
    ports:
      - "${BACKEND_PORT}:8000"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - PORT=8000
      - CHOKIDAR_USEPOLLING=true
      - DATABASE_URL=db://postgres:postgres@db:5432/expense_tracker
      - CORS_ORIGIN=${CORS_ORIGIN}
      - REFRESH_TOKEN_SECRET=1234#jfkdjfd
      - ACCESS_TOKEN_SECRET=abcd#efgh
    depends_on:
      db:
        condition: service_healthy # Wait for db to be healthy before starting backend
  db:
    image: postgres:latest
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: expense_tracker
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    environment:
      - VITE_BACKEND_URL=${API_ENDPOINT}/api
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "${FRONTEND_PORT}:3000"

volumes:
  db_data:
